# Generated by Django 5.2 on 2025-04-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_brand_brand_name_en_brand_brand_name_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auction.car')),
            ],
        ),
    ]
